### ISSUE TITLE
Add unit test for validator

### ISSUE THREAD

**Issue by john9hoff** [john9hoff/amazon-gc#3]
Create a unit test file for the validator, `test/util/validator.test.js` and test that the [validator](https://github.com/john9hoff/amazon-gc/blob/master/src/util/validator.js) accepts/rejects various objects and values.

Validator should accept: 

```
const request = {
    amount: 20,
    currencyCode: 'USD',
    partnerId: 'yourPartnerId',
    accessKey: 'yourAccessKey',
    secretKey: 'yourSecretKey',
    environment: 'sandbox',
    endpoint: 'NA',
}
```

Validator should reject any number less than 1, currencyCode/partnerId/accessKey/secretKey that is not a string, environment that is not sandbox or production, and endpoint that is not NA/EU/FE.

**Comment by ntieman** [comment]
I'll take a look at this if you don't mind.

**Comment by john9hoff** [comment]
Thanks for the help, @ntieman ! Closing
